server:
#  address: 192.168.43.202
  port: 8080

jdbc:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&serverTimezone=UTC
    username: root
    password: 111

mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.example.demo.entity
